# Change these first
owner: stefan-hoeltker-nextn # Your GitHub organization or username, where this repository lives
repo: niko-uptime # The name of this repository

sites:
  - name: Frontend
    url: https://niko.neuenhauser.de
  - name: Keycloak
    url: https://niko.neuenhauser.de/auth/realms/niko-prod
  - name: User API
    url: https://niko.neuenhauser.de/api/user/q/health
  - name: Notification API
    url: https://niko.neuenhauser.de/api/notification/q/health
  - name: Mitarbeiter API
    url: https://niko.neuenhauser.de/api/ma/q/health
  - name: AZ API
    url: https://niko.neuenhauser.de/api/az/q/health
  - name: Geschaeftspartner Portal API
    url: https://niko.neuenhauser.de/api/gpp/q/health
  - name: Marktplatz API
    url: https://niko.neuenhauser.de/api/mp/q/health
  - name: Dealer Portal News API
    url: https://niko.neuenhauser.de/api/news/ut/q/health
  - name: Chat API
    url: https://niko.neuenhauser.de/api/chat/q/health
  - name: Q&A API
    url: https://niko.neuenhauser.de/api/qa/q/health
  - name: Teamkalender API
    url: https://niko.neuenhauser.de/api/tk/q/health
  - name: Controlling Portal API
    url: https://niko.neuenhauser.de/api/cp/q/health


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /niko-uptime
  logoUrl: https://raw.githubusercontent.com/stefan-hoeltker-nextn/niko-uptime/master/assets/NIKO_APP.svg
  name: NIKO-Upptime
  introTitle: 
  introMessage: Das ist die Status Page für NIKO
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Jira Project
      href: https://nextn.atlassian.net/jira/software/projects/NMA/boards/59
    - title: Sources
      href: https://bitbucket.org/nextn/workspace/projects/NIKO      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
